apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bookstore-ui
  labels:
    app: bookstore-ui
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bookstore-ui
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: bookstore-ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
