name: Bookstore API CI/CD

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: bookstore-ui-arc
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: public.ecr.aws
          username: ${{ secrets.AWS_ACCESS_KEY_ID }}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get short commit hash
        id: commit_hash
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          cache-from: type=gha
          cache-to: type=gha
          push: true
          tags:
            "public.ecr.aws/${{ vars.AWS_ECR_ALIAS }}/bookstore-ui:${{ env.TAG }}"

  deploy:
    runs-on: bookstore-ui-arc
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Get short commit hash
        id: commit_hash
        run: |
          TAG=$(git rev-parse --short HEAD)
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Deploy with Helm
        run: >-
          helm upgrade ui ./helm 
          --set image.repository=public.ecr.aws/${{ vars.AWS_ECR_ALIAS }}/bookstore-ui
          --set image.tag=${{ env.TAG }}
          --install --create-namespace --atomic -n bookstore-prod
